# Generated by Django 3.2.8 on 2021-10-27 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorycycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorcycle_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('motorcycle_model', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='static/not_available.png', upload_to='static/product_images/')),
                ('vin', models.CharField(max_length=17)),
                ('manufactured_year', models.IntegerField(default=2000)),
                ('real_km', models.IntegerField(default=0)),
                ('actual_km', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('personal_info', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SoldPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moto_app.motorycycle')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='static/not_available.png', upload_to='static/product_images/')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moto_app.owner')),
            ],
        ),
        migrations.AddField(
            model_name='motorycycle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moto_app.owner'),
        ),
    ]
