# Generated by Django 3.2.8 on 2021-11-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='unit_measurement',
            field=models.CharField(choices=[('l', 'l'), ('buc', 'pcs'), ('kg', 'kg'), ('hr', 'hr')], default='hr', max_length=20),
            preserve_default=False,
        ),
    ]
