# Generated by Django 3.2.8 on 2021-11-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto_app', '0003_auto_20211101_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='item_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
